### ISSUE TITLE
On two patches that may attempt to do the same things, what's better?

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/crunch#14]
On February 16 of 2014 @gimhael committed the patch 4a63c5a491897a8fb9bef1ce0cfd2774c412c361 named “_Linux64 compilation fixes._” doing this:

```diff
-  size_t new_capacity = min_new_capacity;
+  ptr_bits_t new_capacity = min_new_capacity;
   if ((grow_hint) && (!math::is_power_of_2(new_capacity)))
     new_capacity = math::next_pow2(new_capacity);
```

I submitted this patch as PR https://github.com/BinomialLLC/crunch/pull/13 to @BinomialLLC on July 23 of 2017 in hope to get it upstreamed but the patch never got merged neither the submission got an answer for unknown reason. This PR is tracked on our side in #2.

I notice today that @richgel999 merged on October 9 of 2020 the PR https://github.com/BinomialLLC/crunch/pull/25 with the patch 3a445a94cde7fb5cc26e677322785e7e85531a10 by @griffin2000 committed on November 13 of 2018 and named “_Avoid ambiguity error on GCC_” that seems to touch the same code, but doing different things instead:

```diff
       size_t new_capacity = min_new_capacity;
-      if ((grow_hint) && (!math::is_power_of_2(new_capacity)))
-         new_capacity = math::next_pow2(new_capacity);
+	  if ((grow_hint) && (!math::is_power_of_2((uint64)new_capacity)))
+		  new_capacity = math::next_pow2((uint64)new_capacity);
```

1. Are the two patches meant to fix the same bug?
2. Which implementation is the best one?

**Comment by illwieckz** [comment]
I notice I reported on July 23 of 2017 at @BinomialLLC the issue https://github.com/BinomialLLC/crunch/issues/11 as the one fixed by gimhael's patch submitted as PR https://github.com/BinomialLLC/crunch/pull/13, the issue was named “_ambiguous calls prevents compilation (gcc, clang)_” and reported this kind of compilation error:

```llvm
crn_vector.cpp:26:53: error: call of overloaded ‘next_pow2(size_t&)’ is ambiguous
          new_capacity = math::next_pow2(new_capacity);
                                                     ^
In file included from crn_core.h:173:0,
                 from crn_vector.cpp:3:
crn_math.h:84:21: note: candidate: crnlib::uint32 crnlib::math::next_pow2(crnlib::uint32)
       inline uint32 next_pow2(uint32 val)
                     ^~~~~~~~~
crn_math.h:95:21: note: candidate: crnlib::uint64 crnlib::math::next_pow2(crnlib::uint64)
       inline uint64 next_pow2(uint64 val)
```

```llvm
crn_vector.cpp:25:60: error: call of overloaded ‘is_power_of_2(size_t&)’ is ambiguous
       if ((grow_hint) && (!math::is_power_of_2(new_capacity)))
                                                            ^
In file included from crn_core.h:173:0,
                 from crn_vector.cpp:3:
crn_math.h:59:19: note: candidate: bool crnlib::math::is_power_of_2(crnlib::uint32)
       inline bool is_power_of_2(uint32 x) { return x && ((x & (x - 1U)) == 0U); }
                   ^~~~~~~~~~~~~
crn_math.h:60:19: note: candidate: bool crnlib::math::is_power_of_2(crnlib::uint64)
       inline bool is_power_of_2(uint64 x) { return x && ((x & (x - 1U)) == 0U); }
                   ^~~~~~~~~~~~~
```

The issue also reported that the problem was faced on both GCC and LLVM's clang.

So it looks like the two patches are targetting the same issue.

**Comment by illwieckz** [comment]
@slipher or @DolceTriade do you have an opinion on which patch may be better and why?

**Comment by slipher** [comment]
Yes they are fixing the same issue. gimhael's one seems nicer.

**Comment by illwieckz** [comment]
Do the other patch would work on non-64bit systems?

**Comment by slipher** [comment]
> Do the other patch would work on non-64bit systems?

Yes

**Comment by illwieckz** [comment]
OK, if both does the same but the one we already merged looks nicer we can keep it then.
