### ISSUE TITLE
known macOS fixes to pull

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/crunch#16]
I noticed there are some macOS-related fixes in that fork: https://github.com/xuewuli/crunch

Those fixes are mixed with other related features so some manpower is required to extract the fixes we may want before merging them.

Currently, the crn lib (the part integrated in the engine) is known to build on macOS, but the crunch tool is known to not build yet, so we may be interested in some of these fixes.

I open that issue to not forget about those fixes and their availability.

**Comment by illwieckz** [comment]
The commit message explicitly talks about iOS so maybe there is some non-x86 fixes as well there.

**Comment by illwieckz** [comment]
See also: https://github.com/Unity-Technologies/crunch/pull/15

**Comment by illwieckz** [comment]
The fixes from https://github.com/Unity-Technologies/crunch/pull/15 by @blaztinn look easier to review as the one in https://github.com/xuewuli/crunch by @xuewuli is like a jumbo commit, so we may start with https://github.com/Unity-Technologies/crunch/pull/15 and then look at https://github.com/xuewuli/crunch to see if there are extra stuff to cherry-pick.

**Comment by illwieckz** [comment]
@ArctypeZach would you be able to merge https://github.com/Unity-Technologies/crunch/pull/15 on top of our tree on your side and,

1. test it on mac to check if it works on your side, if possible on M1 too,
2. and eventually review the code?

**Comment by ArctypeZach** [comment]
Yup - can do over the weekend

**Comment by illwieckz** [comment]
Done:

- https://github.com/DaemonEngine/crunch/pull/33
